services:
  db:
    image: postgres:15
    container_name: prop2p-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-prop2p}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prop2p}
      POSTGRES_DB: ${POSTGRES_DB:-prop2p}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prop2p-prod

  backend:
    build:
      context: ./backend
      target: runtime
    container_name: prop2p-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-prop2p}:${POSTGRES_PASSWORD:-prop2p}@db:5432/${POSTGRES_DB:-prop2p}
      NODE_ENV: production
      PORT: 8000
      CORS_ORIGINS: ${CORS_ORIGINS:-https://pro2p2.xyz,https://www.pro2p2.xyz}
      PUBLIC_API_URL: ${PUBLIC_API_URL:-https://pro2p2.xyz/api}
      PUBLIC_APP_URL: ${PUBLIC_APP_URL:-https://pro2p2.xyz}
      JWT_SECRET: ${JWT_SECRET:-change-me-in-prod}
      ADMIN_EMAILS: ${ADMIN_EMAILS:-d.mokronos@gmail.com,dmokronos@inbox.ru,pro2p2manager@gmail.com}
      # SMTP (SendPulse)
      SMTP_HOST: ${SMTP_HOST:-smtp-pulse.com}
      SMTP_PORT: ${SMTP_PORT:-465}
      SMTP_SECURE: ${SMTP_SECURE:-true}
      SMTP_USER: ${SMTP_USER:-d.mokronos@gmail.com}
      SMTP_PASS: ${SMTP_PASS:-THfYDX75aP}
      MAIL_FROM: ${MAIL_FROM:-"ProP2P <no-reply@pro2p2.xyz>"}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prop2p-prod

  frontend:
    build:
      context: ./frontend
      target: runner
    container_name: prop2p-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://pro2p2.xyz/api}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prop2p-prod

volumes:
  db_data:

networks:
  prop2p-prod:
    driver: bridge
