name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Typecheck backend
        working-directory: backend
        run: npm run typecheck

      - name: Typecheck frontend
        working-directory: frontend
        run: npm run typecheck

      - name: Lint backend
        working-directory: backend
        run: npm run lint

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Run backend unit tests
        working-directory: backend
        run: npm test -- --ci

      - name: Run backend e2e tests
        working-directory: backend
        run: npm run test:e2e -- --ci

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t prop2p-backend:ci ./backend

      - name: Build frontend image
        run: docker build -t prop2p-frontend:ci ./frontend
