name: Deploy to VPS
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            REPO_DIR=${{ secrets.REPO_DIR || '/srv/prop2p' }}
            if [ ! -d "$REPO_DIR/.git" ]; then
              echo "ERROR: Repo directory $REPO_DIR not found or not a git repo. Clone it once on the server:"
              echo "  sudo mkdir -p $REPO_DIR && sudo chown $USER:$USER $REPO_DIR"
              echo "  git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY $REPO_DIR"
              exit 1
            fi
            cd "$REPO_DIR"
            git fetch --all --prune
            git reset --hard origin/main
            docker compose -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.prod.yml up -d --build
            docker system prune -f || true
